In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('clean_df.csv',index_col = 0)
df.head()

,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPLN,_HCVU652,_TOTINDA,_EXTETH3,_ALTETH3,_DENVST3,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_RACEPR1,_SEX
0,1.0,3.0,1.0,1.0,9.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,2.0
1,1.0,1.0,3.0,1.0,1.0,2.0,2.0,NaN,2.0,1.0,1.0,3.0,2.0,7.0,2.0
2,1.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,1.0,1.0,3.0,2.0,1.0,1.0
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,2.0,2.0,2.0,1.0,2.0,1.0,1.0
4,1.0,1.0,2.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,3.0,2.0,1.0,1.0

In [ ]:
df.rename(columns={'ancienne_colonne': 'nouvelle_colonne'}, inplace=True)